version: '3.7'
services:
    #front-end:
    #    container_name: front
    #    image: app_linux
    #    stdin_open: true
    #    build:
    #      context: ../app
    #      dockerfile: dockerfile.dev
    #    volumes:
    #      - ../app/:/app
    #    ports:
    #        - "80:80"
    #        - "3000:3000"
    #    networks:
    #            - internal
    #    environment:
    #      - CHOKIDAR_USEPOLLING=true
    #    restart: on-failure
    backend:
        container_name: server
        build:
          context: ../server
          dockerfile: Dockerfile
        restart: on-failure
