version: "3.7"
services:
  front-end:
    container_name: front
    build:
      context: ../rps-ui
      dockerfile: dockerfile
    ports:
      - "80:80"
    restart: on-failure
  backend:
    container_name: server
    build:
      context: ../server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: on-failure
